openapi: 3.0.3
info:
  title: file service
  description: |
    file system that managing upload/download files
  version: 1.0.0
servers:
  - url: 'http://localhost:8088/api/v1'
    description: localhost server
tags:
  - name: files
paths:
  /spaces:
    post:
      summary: create a space
      operationId: createSpace
      tags:
        - files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceAddRequest'

      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceResponse'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /folders:
    post:
      summary: create a folder
      operationId: createFolder
      tags:
        - files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderAddRequest'

      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FolderResponse'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /files:
    post:
      summary: create a file
      operationId: createFile
      tags:
        - files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileAddRequest'

      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /files/{fileId}:
    get:
      summary: get a file
      operationId: getFile
      tags:
        - files
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: integer
            description: file id
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /files/{fileId}/content:
    get:
      summary: download the file content
      operationId: downloadFile
      tags:
        - files
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: integer
            description: file id
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        404:
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'

components:
  schemas:

    SpaceAddRequest:
      type: object
      description: |
        the Space add request
      allOf:
        - $ref: '#/components/schemas/Space'
      example:
        name: stc-assessments
        userPermissionId: 1
        groupPermissionId: 1


    SpaceResponse:
      type: object
      description: |
        the Space response
      allOf:
        - type: object
          properties:
            id:
              description: |
                the Space id
              type: integer
        - $ref: '#/components/schemas/Space'
        - $ref: '#/components/schemas/Links'
      example:
        id: 1
        name: stc-assessments
        userPermissionId: 1
        groupPermissionId: 1
        location: "/"
        _links:
          - rel: self
            href: http://localhost:8088/api/v1/spaces
    Space:
      type: object
      description: |
        the Space model
      required:
        - name
        - userPermissionId
        - groupPermissionId
      allOf:
        - $ref: '#/components/schemas/MetaData'

    FolderAddRequest:
      type: object
      description: |
        the folder add request
      allOf:
        - $ref: '#/components/schemas/Folder'
      example:
        name: backend
        parentId: 1
        userPermissionId: 1
        groupPermissionId: 1
    FolderResponse:
      type: object
      description: |
        the folder response
      allOf:
        - type: object
          properties:
            id:
              description: |
                the file id
              type: integer
        - $ref: '#/components/schemas/Folder'
        - $ref: '#/components/schemas/Links'
      example:
        id: 2
        parentId: 1
        name: backend
        userPermissionId: 1
        groupPermissionId: 1
        location: "/backend"
        _links:
          - rel: self
            href: http://localhost:8088/api/v1/folders

    Folder:
      type: object
      description: |
        the Folder model
      required:
        - name
        - parentId
      allOf:
        - $ref: '#/components/schemas/FileAndFolderMetaData'

    FileAddRequest:
      type: object
      description: |
        the file add request
      allOf:
        - $ref: '#/components/schemas/File'
      example:
        name: assessment.pdf
        content: JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFn...
        parentId: 2
        userPermissionId: 1
        groupPermissionId: 1
    FileResponse:
      type: object
      description: |
        the file response
      allOf:
        - type: object
          properties:
            id:
              description: |
                the file id
              type: integer
        - $ref: '#/components/schemas/File'
        - $ref: '#/components/schemas/Links'
      example:
        id: 1
        content: JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFn...
        parentId: 2
        name: assessment.pdf
        userPermissionId: 1
        groupPermissionId: 1
        location: "/backend/assessment.pdf"
        _links:
          - rel: self
            href: http://localhost:8088/api/v1/files
          - rel: download
            href: http://localhost:8088/api/v1/files/1/content

    File:
      type: object
      description: |
        the Folder model
      required:
        - name
        - content
        - parentId
      allOf:
        - type: object
          properties:
            content:
              description: |
                the File base64 content
              type: string
        - $ref: '#/components/schemas/FileAndFolderMetaData'

    MetaData:
      type: object
      properties:
        name:
          description: |
            the Name
          type: string
        userPermissionId:
          description: |
            the user PermissionId
          type: integer
        groupPermissionId:
          description: |
            the Group Permission Id
          type: integer
        location:
          description: |
            the item location
          type: string
    FileAndFolderMetaData:
      type: object
      allOf:
        - type: object
          properties:
            parentId:
              description: |
                the parent id
              type: integer
        - $ref: '#/components/schemas/MetaData'
    Links:
      type: object
      properties:
        _links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    Link:
      type: object
      properties:
        rel:
          type: string
          example: self
        href:
          type: string


    ErrorDetails:
      type: object
      required:
        - code
        - message
      properties:
        date:
          type: string
          format: datetime
        status:
          type: string
        error:
          type: string
        uri:
          type: string
        message:
          type: string
